api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform/resources'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    title: 'SF5 + API Platform and Docker'
    description: 'An awesome API built with Symfony 5.0, PHP 7.4 and API Platform'
    version: 1.0
    show_webby: false
